export const ErrorCodes = {
  // Authentication errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // Resource errors
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  // Order errors
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  SLOT_NOT_AVAILABLE: 'SLOT_NOT_AVAILABLE',
  SLOT_EXPIRED: 'SLOT_EXPIRED',
  STORE_NOT_ACCEPTING_ORDERS: 'STORE_NOT_ACCEPTING_ORDERS',
  STORE_CLOSED: 'STORE_CLOSED',

  // Payment errors
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_DECLINED: 'PAYMENT_DECLINED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',

  // Loyalty errors
  INSUFFICIENT_POINTS: 'INSUFFICIENT_POINTS',
  REWARD_NOT_AVAILABLE: 'REWARD_NOT_AVAILABLE',

  // Gift card errors
  GIFT_CARD_INVALID: 'GIFT_CARD_INVALID',
  GIFT_CARD_EXPIRED: 'GIFT_CARD_EXPIRED',
  GIFT_CARD_ALREADY_REDEEMED: 'GIFT_CARD_ALREADY_REDEEMED',

  // External service errors
  TOAST_POS_ERROR: 'TOAST_POS_ERROR',
  STRIPE_ERROR: 'STRIPE_ERROR',
  DELIVERY_SERVICE_ERROR: 'DELIVERY_SERVICE_ERROR',

  // Rate limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // System errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
